---
# tasks file for packages

## homebrew packages
- name: ensure latest homebrew installed
  homebrew:
    state: latest
    update_homebrew: yes
- name: cleanup homebrew
  command: brew cleanup
- name: ensure latest brew packages installed
  homebrew:
    name: 
     - git
     - imagemagick
     - htop
     - tree
     - coreutils
     - telnet
     - ruby
     - fish
     - node
     - yarn
     - python
     - htop 
     - watchman 
     - tree
    state: latest

# gem dependencies
- name: ensure latest bundler is installed
  gem:
    name: bundler
    state: latest
- name: ensure latest cocoapods installed
  gem:
    name: cocoapods
    state: latest
- name: ensure latest fastlane installed
  gem:
    name: fastlane
    state: latest
